v1.0.0

diff --git a/.github/workflows/test-kitchen.yml b/.github/workflows/test-kitchen.yml
--- a/.github/workflows/test-kitchen.yml
+++ b/.github/workflows/test-kitchen.yml
@@ -1,5 +1,3 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Cookbooks Upload
 
 on: [ push, workflow_dispatch ]
@@ -33,23 +31,51 @@ jobs:
         run: |
           sudo yum update -y
           sudo yum install -y yum-utils device-mapper-persistent-data lvm2
-          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
-          sudo yum install -y docker-ce docker-ce-cli containerd.io
+          sudo yum install -y docker
           docker -v
           sudo usermod -aG docker $USER
-          sudo chmod 666 /run/docker.sock
+          sudo chmod 666 /usr/lib/systemd/system/docker.socket
+          sudo chmod 666 /var/run/docker.sock
           sudo service docker start
+          sudo systemctl enable docker
           service docker status
+      
+      - name: Docker Running?
+        continue-on-error: true
+        id: check-docker-status
+        run: sudo service docker status
+
+      - name: Start Docker
+        if: steps.check-docker-status.outcome == 'failure'
+        run: sudo service docker start
 
       - name: Kitchen Converge
-        run: echo "Skipping kitchen converge for this sample cookbook"
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        run: |
+          kitchen destroy
+          knife node list -c .chef/config.rb | grep "default-*" | xargs knife node delete -y -c .chef/config.rb || echo "node deletion failed somehow"
+          knife client list -c .chef/config.rb | grep "default-*" | xargs knife client delete -y -c .chef/config.rb || echo "client delete failed somehow"
+          docker container prune --force
+          docker volume prune --force
+          docker network prune --force
+          docker system prune --force
+          kitchen list
+          kitchen create
+          kitchen converge
           
       - name: Kitchen Test
-        run: echo "Skipping kitchen test for this sample cookbook"
-        
-      - name: Cleanup Containers 
+        run: kitchen verify
+      
+      - name: Cleanup Containers
         if: always()
-        run: echo "Skipping kitchen test for this sample cookbook"
+        run: kitchen destroy
+
+      - name: Delete node/client from Chef Server
+        if: always()
+        run: |
+          knife node list -c .chef/config.rb | grep "default-*" | xargs knife node delete -y -c .chef/config.rb || echo "node deletion failed somehow"
+          knife client list -c .chef/config.rb | grep "default-*" | xargs knife client delete -y -c .chef/config.rb || echo "client delete failed somehow"
 
   Cookbook-Upload:
     runs-on: self-hosted
@@ -60,3 +86,4 @@ jobs:
           rm Berksfile.lock || echo 'Removeal not took place.'
           berks install
           berks upload --force
+          
